sudo: false

language: erlang

otp_release:
  - 17.3
  - 17.1

env:
  matrix:
    - CC=clang
    - CC=gcc

before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.2.zip
  - unzip -d elixir v1.0.2.zip
  - $CC --version

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get

script: mix test

after_script:
  - MIX_ENV=docs mix inch.report

after_success:
  - mix compile
  - mix coveralls.travis
