sudo: false
language: elixir
elixir: 1.0.4
otp_release:
  - 17.5
  - 17.4

env:
  matrix:
    - CC=clang
    - CC=gcc

after_script:
  - MIX_ENV=docs mix inch.report

after_success:
  - mix compile
  - mix coveralls.travis
